name: Release jfvm to Homebrew

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'

      - name: Build binary
        run: |
          mkdir -p dist/jfvm-${{ github.ref_name }}
          go build -o dist/jfvm-${{ github.ref_name }}/jfvm

      - name: Create tarball
        run: |
          cd dist
          tar -czf jfvm-${{ github.ref_name }}.tar.gz jfvm-${{ github.ref_name }}

      - name: Compute SHA256
        id: sha
        run: echo "sha=$(shasum -a 256 dist/jfvm-${{ github.ref_name }}.tar.gz | awk '{print $1}')" >> $GITHUB_OUTPUT

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/jfvm-${{ github.ref_name }}.tar.gz

      - name: Generate Homebrew formula
        run: |
          cat <<EOF > jfvm.rb
          class Jfvm < Formula
            desc "Manage multiple versions of JFrog CLI"
            homepage "https://github.com/${{ github.repository }}"
            url "https://github.com/${{ github.repository }}/releases/download/${{ github.ref_name }}/jfvm-${{ github.ref_name }}.tar.gz"
            sha256 "${{ steps.sha.outputs.sha }}"
            version "${{ github.ref_name }}"

            def install
              bin.install "jfvm"
            end

            test do
              system "#{bin}/jfvm", "--help"
            end
          end
          EOF

      - name: Upload formula to artifacts
        uses: actions/upload-artifact@v3.1.3
        with:
          name: jfvm.rb
          path: jfvm.rb
